CREATE TABLE IF NOT EXISTS Students(studId INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,class TEXT,mark TEXT);
INSERT or IGNORE INTO Students VALUES (1, 'Paresh', 'X', '550');
INSERT or IGNORE INTO Students VALUES (2, 'Rahul', 'XI', '650');
INSERT or IGNORE INTO Students VALUES (3, 'Ramesh', 'XII', '525');